google_oauth2:
  enabled: true
  params: {}

facebook:
  enabled: true
  params:
    scope: public_profile,email
    info_fields: email,name

twitter:
  enabled: true
  params: {}

github:
  enabled: true
  params:
    scope: user:email

instagram:
  enabled: true
  params: {}

linkedin:
  enabled: true
  params: {}
