auth_provider:
  enabled: true
  params:
    namespace: 'auth.dev'
    provider_ignores_state: false

google_oauth2:
  enabled: true

facebook:
  enabled: true
  params:
    scope: public_profile,email
    info_fields: email,name

twitter:
  enabled: true

github:
  enabled: true
  params:
    scope: user:email

instagram:
  enabled: true

linkedin:
  enabled: true
